basePath: /api/vi
definitions:
  handler.Description:
    properties:
      comment:
        type: string
      score:
        type: integer
    required:
    - comment
    - score
    type: object
  handler.user:
    properties:
      id:
        description: 一定要输入的加上了required
        type: string
      password:
        type: string
    required:
    - id
    - password
    type: object
host: localhost:8080
info:
  contact:
    email: 2105753640@qq.com
    name: yyj
  description: '"赚圈圈API 返回的goods如果其中的goodsin为yes代表它可以进行交易，即：未下架"'
  termsOfService: http://swagger.io/terrms/
  title: miniproject
  version: 1.0.0
paths:
  /money/entrance:
    post:
      consumes:
      - application/json
      description: '"登录的api"'
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.user'
      produces:
      - application/json
      responses:
        "200":
          description: msg":"login successfully"}
          schema:
            type: string
        "401":
          description: msg":"error happened"}
          schema:
            type: string
      summary: '"用户登录"'
      tags:
      - Givecomment
  /money/goods/addition:
    post:
      consumes:
      - multipart/form-data
      description: '"新增一个商品时的api"'
      parameters:
      - description: 商品图二进制文件
        in: formData
        name: avatar
        required: true
        type: file
      - description: 联系方式二进制文件
        in: formData
        name: way
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: msg":"upload successfully"}
          schema:
            type: string
        "500":
          description: msg":"error happened"}
          schema:
            type: string
      summary: '"上架商品"'
      tags:
      - New goods
  /money/goods/comment:
    post:
      consumes:
      - application/json
      description: '"用户做出评价，点击评价时的api"'
      parameters:
      - description: comment
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/handler.Description'
      - description: goodsid
        in: query
        name: goodsid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg":"give successfully"}
          schema:
            type: string
        "500":
          description: msg":"error happened"}
          schema:
            type: string
      summary: '"用户对某个商品的评论"'
      tags:
      - Givecomment
  /money/goods/comments:
    get:
      consumes:
      - application/json
      description: '"商品详情页点击评价时的api "scores":所有分值情况, "infor":"评论信息以及学号""'
      parameters:
      - description: goodsid
        in: query
        name: goodsid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: infor":[]tables.Comment,"score":All}
          schema:
            type: string
        "500":
          description: msg":"err"}
          schema:
            type: string
      summary: '"获取某个商品的所有评论"'
      tags:
      - Comment
  /money/goods/deletion:
    get:
      consumes:
      - application/json
      description: '"下架商品的api"'
      parameters:
      - description: goodsid
        in: query
        name: goodsid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg":"delete successfully"}
          schema:
            type: string
        "500":
          description: msg":"error happened"}
          schema:
            type: string
      summary: '"商家下架商品"'
      tags:
      - Delete
  /money/goods/feedback:
    post:
      consumes:
      - application/json
      description: '"举报的api"'
      parameters:
      - description: goodsid
        in: query
        name: goodsid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg":"举报成功!"}
          schema:
            type: string
        "500":
          description: msg":"error happened"}
          schema:
            type: string
      summary: '"接收举报"'
      tags:
      - Feedback
  /money/goods/scanning:
    get:
      consumes:
      - application/json
      description: '"点击进入商品详情页的api"'
      parameters:
      - description: goodsid
        in: query
        name: goodsid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg":"success","infor":tables.User,"user":tables.User,"tips":"如果goodsin是no则代表已经下架，此时则不显示开启交易按钮"}
          schema:
            type: string
        "500":
          description: msg":"error happened"}
          schema:
            type: string
      summary: '"查询某个商品的详细信息"'
      tags:
      - Scan
  /money/goods/shopping:
    get:
      consumes:
      - application/json
      description: '"点击购买时的api"'
      parameters:
      - description: goodsid
        in: query
        name: goodsid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg":"success","img":"联系方式对应的url"}
          schema:
            type: string
        "500":
          description: msg":"error happened"}
          schema:
            type: string
      summary: '"用户进行购买"'
      tags:
      - Buy
  /money/homepage:
    post:
      consumes:
      - application/json
      description: '"order=1->返回前十个商品的内容，summary不需要展示出来，是在商品详情页里，主页的api"'
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg":"success","infor":[]tables.Good}
          schema:
            type: string
        "500":
          description: msg":"error"}
          schema:
            type: string
      summary: '"主页内容"'
      tags:
      - Homepage
  /money/message:
    get:
      consumes:
      - application/json
      description: '"信息已根据时间按升序排列，id越大越新，消息通知的api"'
      produces:
      - application/json
      responses:
        "200":
          description: msg":"success","infor":[]tables.Message}
          schema:
            type: string
        "500":
          description: error happened
      summary: '"返回用户购买、收藏后的信息"'
      tags:
      - Return Message
  /money/my/cancellation:
    post:
      consumes:
      - application/json
      description: '"在购物车里取消收藏的api"'
      parameters:
      - description: goodsid
        in: query
        name: goodsid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg":"success"}
          schema:
            type: string
        "500":
          description: msg":"error happened"}
          schema:
            type: string
      summary: '"取消收藏"'
      tags:
      - Cancel
  /money/my/cart:
    get:
      consumes:
      - application/json
      description: '"购物车"'
      produces:
      - application/json
      responses:
        "200":
          description: msg":"check successfully","infot":[]tables.Good}
          schema:
            type: string
        "204":
          description: msg":"check successfully","infot":"nothing"}
          schema:
            type: string
        "500":
          description: msg":"error happened"}
          schema:
            type: string
      summary: '"查看我的购物车"'
      tags:
      - MYCart
  /money/my/goods:
    get:
      consumes:
      - application/json
      description: '"橱窗"'
      produces:
      - application/json
      responses:
        "200":
          description: msg":"check successfully","infot":[]tables.Good}
          schema:
            type: string
        "500":
          description: msg":"error happened"}
          schema:
            type: string
      summary: '"查看我的橱窗"'
      tags:
      - MYgoods
  /money/my/goods/fish:
    get:
      consumes:
      - application/json
      description: '"点击确认完成时的api"'
      parameters:
      - description: goodsid
        in: query
        name: goodsid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg":"success"}
          schema:
            type: string
        "500":
          description: error happened
      summary: '"商家完成订单"'
      tags:
      - Finish trade
  /money/my/goods/unfish:
    get:
      consumes:
      - application/json
      description: '"返回订单,需要点完成的是‘my sell’->[]string 是与我做交易的人的id,因为一个商品可能被多个人购买，所以string切片的长度就是‘完成订单’的订单数,点评价的是‘my
        buy’"'
      produces:
      - application/json
      responses:
        "200":
          description: msg":"success","my buy":[]Two,"my sell":map[Two][]string}
          schema:
            type: string
        "500":
          description: error happened"}
          schema:
            type: string
      summary: '"返回用户与卖家未完成的订单"'
      tags:
      - return trade
  /money/my/message:
    post:
      consumes:
      - application/json
      description: '"我的个人信息的api"'
      produces:
      - application/json
      responses:
        "200":
          description: msg":"avatar 是头像对应的url","infor":tables.User}
          schema:
            type: string
        "500":
          description: msg":"error happened","infor":tables.User}
          schema:
            type: string
      summary: '"返回我的信息"'
      tags:
      - Message
  /money/new_star:
    patch:
      consumes:
      - application/json
      description: '"添加至购物车时的api"'
      parameters:
      - description: goodsid
        in: query
        name: goodsid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg":"add successfully"}
          schema:
            type: string
        "500":
          description: msg":"error happened"}
          schema:
            type: string
      summary: '"新增收藏"'
      tags:
      - Add
  /money/search:
    post:
      consumes:
      - application/json
      description: '"order=1->返回前十个商品的内容，summary不需要展示出来-》在商品详情页里,搜索的api"'
      parameters:
      - description: content
        in: formData
        name: content
        required: true
        type: string
      - description: page
        in: query
        name: page
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg":"search successfully","infor":[]tables.Good}
          schema:
            type: string
        "204":
          description: msg":"find nothing"}
          schema:
            type: string
      summary: '"搜索"'
      tags:
      - Search
schemes:
- http
swagger: "2.0"
